version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-tests
    volumes:
      - ./allure-results:/app/allure-results
      - ./screenshots:/app/screenshots
      - ./trace:/app/trace
      - ./todo-logs:/app/todo-logs
    environment:
      - BASE_URL=https://react-cool-todo-app.netlify.app
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PW=${ADMIN_PW:-password}
      - HEADLESS=false
    command: /bin/sh -c "xvfb-run -a pytest tests/ --alluredir=./allure-results --clean-alluredir && sleep 5"
    depends_on:
      - allure

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-server
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 2
      KEEP_HISTORY: "TRUE"
    volumes:
      - ./allure-results:/app/allure-results
